README.md

* change signers and validators to workers
* specify how message id should be formatted

docs: cleanup README

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

chore: add issue and PR template

---

Cargo.lock
ampd/src/handlers/evm_verify_msg.rs
contracts/connection-router/src/state.rs
contracts/connection-router/src/types.rs
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/error.rs
contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/state.rs
contracts/voting-verifier/tests/tests.rs
packages/axelar-wasm-std/Cargo.toml
packages/axelar-wasm-std/src/lib.rs
packages/axelar-wasm-std/src/operators.rs
packages/axelar-wasm-std/src/voting.rs

* Add ConfirmWorkerSet execute msg
* Add IsWorkerSetConfirmed query
AXE-1536

feat(voting-verifier): confirm worker set update

---

Cargo.lock
ampd/Cargo.toml
ampd/src/broadcaster.rs
ampd/src/config.rs
ampd/src/lib.rs
ampd/src/queue/queued_broadcaster.rs
ampd/src/report.rs
ampd/src/state.rs
ampd/src/tofnd/grpc.rs
ampd/src/tofnd/mod.rs

feat: request tofnd keygen if not set in the state on boot

---

ampd/src/handlers/evm_verify_worker_set.rs
ampd/src/handlers/mod.rs
ampd/src/types.rs

feat: event decoding for evm verify worker set handler

---

ampd/src/broadcaster.rs
ampd/src/broadcaster/dec_coin.rs
ampd/src/config.rs
ampd/src/evm/mod.rs
ampd/src/handlers/config.rs
ampd/src/tests/config_template.toml
ampd/src/tofnd/mod.rs
ampd/src/url.rs
contracts/gateway/tests/tests.rs

https://axelarnetwork.atlassian.net/browse/AXE-1845

feat: ampd config can get serialized

---

.github/workflows/basic.yml
contracts/multisig/src/msg.rs
contracts/service-registry/src/msg.rs

[Details](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/18?modal=detail&selectedIssue=AXE-1833)
Fail tests if there is a warning

chore: fail tests when there's warnings

---

contracts/multisig-prover/src/execute.rs

adds `save_next_worker_set ` and `get_worker_sets`
cargo test all passes

refactor: refactor some worker_set functions

---

Cargo.lock
Cargo.toml
contracts/aggregate-verifier/Cargo.toml
contracts/batching/Cargo.toml
contracts/connection-router/Cargo.toml
contracts/gateway/Cargo.toml
contracts/multisig-prover/Cargo.toml
contracts/multisig/Cargo.toml
contracts/rewards/Cargo.toml
contracts/service-registry/Cargo.toml
contracts/service-registry/src/contract.rs
contracts/voting-verifier/Cargo.toml
packages/axelar-wasm-std/Cargo.toml

chore: extract cosmwasm dependencies into workspace

---

contracts/aggregate-verifier/src/contract.rs
contracts/aggregate-verifier/src/msg.rs
contracts/aggregate-verifier/tests/mock.rs
contracts/aggregate-verifier/tests/test.rs
contracts/connection-router/src/contract.rs
contracts/connection-router/src/events.rs
contracts/connection-router/src/msg.rs
contracts/connection-router/src/state.rs
contracts/connection-router/tests/mock.rs
contracts/connection-router/tests/test.rs
contracts/gateway/src/contract/execute.rs
contracts/gateway/src/events.rs
contracts/gateway/src/msg.rs
contracts/gateway/src/state.rs
contracts/multisig-prover/src/encoding/bcs.rs
contracts/multisig-prover/src/encoding/mod.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/test/test_data.rs
contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/query.rs
contracts/voting-verifier/src/state.rs
contracts/voting-verifier/tests/tests.rs

https://axelarnetwork.atlassian.net/browse/AXE-1205

refactor: rename NewMessage and make_message_event_new

---

Cargo.lock
contracts/nexus-gateway/Cargo.toml
contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/error.rs
contracts/nexus-gateway/src/lib.rs
contracts/nexus-gateway/src/msg.rs
contracts/nexus-gateway/src/state.rs

feat: define nexus gateway msgs

---

contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/error.rs

refactor: fix ContractError for the nexus gateway contract

---

contracts/rewards/src/msg.rs
doc/src/SUMMARY.md
doc/src/contracts/rewards.md

* change pool_duration to rewards rate
* remove StartRewardsEvent

refactor(rewards): refactor rewards interface

---

Cargo.lock
contracts/multisig-prover/src/execute.rs
contracts/multisig/Cargo.toml
contracts/multisig/src/test/common.rs
contracts/voting-verifier/src/execute.rs
packages/axelar-wasm-std/src/snapshot.rs
packages/axelar-wasm-std/src/voting.rs

Removed some unused fields from the snapshot struct
https://axelarnetwork.atlassian.net/browse/AXE-2194

refactor(Snapshot): remove unused fields from snapshot

---

ampd/src/config.rs
ampd/src/handlers/config.rs
ampd/src/handlers/sui_verify_msg.rs
ampd/src/lib.rs
ampd/src/tests/config_template.toml

feat: config Sui handler

---

Cargo.lock
contracts/connection-router/src/state.rs
contracts/multisig-prover/src/encoding/bcs.rs
contracts/nexus-gateway/Cargo.toml
contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/contract/execute.rs
contracts/nexus-gateway/src/error.rs
contracts/nexus-gateway/src/lib.rs
contracts/nexus-gateway/src/nexus.rs
packages/axelar-wasm-std/src/nonempty/vec.rs

feat: implement the execute method route_to_nexus for the nexus gateway contract

---

Cargo.lock
contracts/connection-router/src/contract.rs
contracts/connection-router/src/msg.rs
contracts/connection-router/src/state.rs
contracts/connection-router/tests/test.rs
contracts/multisig-prover/src/execute.rs
contracts/service-registry/Cargo.toml
contracts/service-registry/src/contract.rs
contracts/service-registry/src/msg.rs
contracts/service-registry/src/state.rs
contracts/service-registry/tests/tests.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/tests/tests.rs

Updates instances of chain_name to use the ChainName datatype, and updated test cases.
run `cargo test`
all test cases pass

refactor: change chain_name datatype from String to ChainName

---

Cargo.lock
contracts/rewards/Cargo.toml
contracts/rewards/src/error.rs
contracts/rewards/src/lib.rs
contracts/rewards/src/msg.rs
contracts/rewards/src/state.rs

Just some basic functions needed for rewards. The logic will come in a later PR.
https://axelarnetwork.atlassian.net/browse/AXE-2159

feat(rewards): state scaffolding

---

Cargo.lock
contracts/rewards/Cargo.toml
contracts/rewards/src/contract/execute.rs
contracts/rewards/src/contract/mod.rs
contracts/rewards/src/lib.rs
contracts/rewards/src/msg.rs
contracts/rewards/src/state.rs
packages/axelar-wasm-std/src/nonempty/uint.rs

* implement logic for updating epoch
https://axelarnetwork.atlassian.net/browse/AXE-2167

feat(rewards): add contract abstraction

---

contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/contract/execute.rs
contracts/nexus-gateway/src/error.rs
contracts/nexus-gateway/src/nexus.rs
contracts/nexus-gateway/src/state.rs

feat: nexus gateway contract route messages to nexus only if they have not been routed yet

---

contracts/rewards/src/contract/execute.rs
contracts/rewards/src/error.rs

https://axelarnetwork.atlassian.net/browse/AXE-2372

feat(rewards): update params

---

Cargo.lock
Cargo.toml
contracts/multisig-prover/src/test/multicontract.rs
contracts/multisig/Cargo.toml
contracts/multisig/src/contract.rs
contracts/multisig/src/msg.rs
contracts/multisig/src/signing.rs
contracts/multisig/src/state.rs

Calls reward contract to record participation during signature submission. Implements grace period to record participation for late signing
https://axelarnetwork.atlassian.net/browse/AXE-2097
In future PR the prover will be updated to optimize the minimum amount of signatures required to construct the proof

feat(multisig): integrate signing with rewards contract

---

doc/src/contracts/multisig.md
doc/src/contracts/multisig_prover.md
doc/src/overview.md

small fix to make diagrams readable

docs: fix diagram color for overview.md

---

contracts/rewards/src/contract.rs
contracts/rewards/src/contract/execute.rs
contracts/rewards/src/contract/mod.rs
contracts/rewards/src/lib.rs

https://axelarnetwork.atlassian.net/browse/AXE-2423

feat(rewards): contract entry points

---

contracts/multisig/src/contract.rs

small refactor
`cargo test` passes

refactor(multisig): refactor key_id usages in start_signing_session

---

contracts/multisig-prover/src/query.rs
contracts/service-registry/src/state.rs

https://axelarnetwork.atlassian.net/browse/AXE-2384

feat(multisig-prover): optimize to construct proof using the minimum amount of signatures required

---

contracts/multisig-prover/src/test/mocks/service_registry.rs
contracts/service-registry/src/contract.rs
contracts/service-registry/src/msg.rs

feat(service-registry): service and worker query

---

contracts/rewards/src/contract/execute.rs
contracts/rewards/src/error.rs
contracts/rewards/src/msg.rs
contracts/rewards/src/state.rs
packages/axelar-wasm-std/src/nonempty/vec.rs
packages/axelar-wasm-std/src/threshold.rs

https://axelarnetwork.atlassian.net/browse/AXE-2419

feat(rewards): distribute rewards for specified epoch

---

contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/state.rs
packages/axelar-wasm-std/src/voting.rs

Context: 
- https://github.com/axelarnetwork/axelar-amplifier/pull/176#discussion_r1382182379
- https://github.com/axelarnetwork/axelar-amplifier/pull/176#discussion_r1382190150
https://axelarnetwork.atlassian.net/browse/AXE-2520

refactor(voting-verifier): update poll functions to remove mutable reference to self and separate side effects

---

Cargo.lock
contracts/multisig/src/contract.rs
contracts/rewards/Cargo.toml
contracts/rewards/src/contract.rs
contracts/rewards/src/contract/execute.rs
contracts/rewards/src/error.rs
contracts/rewards/src/msg.rs
contracts/rewards/src/state.rs
contracts/voting-verifier/src/execute.rs
packages/axelar-wasm-std/src/nonempty/mod.rs
packages/axelar-wasm-std/src/nonempty/uint.rs

Implements execute, handling each case of ExecuteMsg, and fixes some bugs in the rewards contract
https://axelarnetwork.atlassian.net/browse/AXE-2523

feat(rewards): implement execute

---

ampd/src/sui/verifier.rs

In Sui, unlike EVM chains, `CallContract` events are emitted from the caller contract instead of Gateway address. Previously, the verifier incorrectly used `packageId` as the gateway address.
Update event verification logic to use the direct gateway address instead of `packageId` for identifying `CallContract` events in Sui.

fix: use gateway address for event verification

---

contracts/rewards/src/contract.rs

Basic test for the contract endpoints (instantiate and execute).
https://axelarnetwork.atlassian.net/browse/AXE-2524

test(rewards): add simple rewards flow test

---

contracts/connection-router/src/lib.rs
contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/contract/execute.rs
contracts/nexus-gateway/src/error.rs
contracts/nexus-gateway/src/msg.rs
contracts/nexus-gateway/src/nexus.rs

feat: nexus gateway RouteToRouter

---

Cargo.lock
Cargo.toml
integration-tests/Cargo.toml
integration-tests/src/lib.rs
integration-tests/src/test.rs

Code to instantiate all of the contracts in a simulation environment. Can execute contract calls and the contracts will talk to each other. No need for mock contracts.

test: initial setup for integration tests

---

.github/workflows/build-latest-docker-image.yaml

feat(gh-action):  github action build docker image 

---

Cargo.lock
ampd/src/commands/bond_worker.rs
ampd/src/commands/declare_chain_support.rs
ampd/src/commands/mod.rs
ampd/src/commands/register_public_key.rs
ampd/src/main.rs
contracts/connection-router/Cargo.toml
contracts/connection-router/src/state.rs

feat: register public key and declare chain support commands

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/encoding/abi.rs
contracts/multisig-prover/src/encoding/bcs.rs
contracts/multisig-prover/src/encoding/mod.rs
contracts/multisig-prover/src/events.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/msg.rs
contracts/multisig-prover/src/state.rs
contracts/multisig-prover/src/types.rs
integration-tests/tests/message_routing.rs
integration-tests/tests/test_utils/mod.rs

https://axelarnetwork.atlassian.net/browse/AXE-2781

refactor(multisig-prover)!: use CrossChainID in ConstructProof

---

contracts/connection-router/src/contract.rs
contracts/connection-router/src/contract/query.rs
contracts/connection-router/src/msg.rs

https://axelarnetwork.atlassian.net/browse/AXE-2783

feat(connection-router): add query for chain info

---

ampd/src/block_height_monitor.rs
ampd/src/lib.rs

Add a struct to the `App` that keeps track of the current block height on chain

feat(ampd): add block height monitor

---

ampd/src/commands/mod.rs
ampd/src/commands/register_chain_support.rs
ampd/src/main.rs
contracts/service-registry/src/contract.rs
contracts/service-registry/src/msg.rs
contracts/service-registry/tests/tests.rs
integration-tests/tests/test_utils/mod.rs

feat: axe-2791 first step, add denounce chain support to service registry

---

ampd/src/commands/deregister_chain_support.rs
ampd/src/commands/mod.rs
ampd/src/main.rs

feat: add chain support deregistration to ampd src

---

.github/workflows/build-latest-docker-image.yaml

feat: check if image tag already exists before push

---

Cargo.lock
ampd/Cargo.toml
ampd/src/config.rs
ampd/src/handlers/config.rs
ampd/src/json_rpc.rs
ampd/src/lib.rs
ampd/src/tests/config_template.toml

feat(ampd): add timeout to the EVM/SUI JSON-RPC clients

---

contracts/service-registry/tests/test_utils/mod.rs
contracts/service-registry/tests/tests.rs

[AXE-3042]
[AXE-3042]: https://axelarnetwork.atlassian.net/browse/AXE-3042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: migrate base service registry test setup to test utils

---

contracts/multisig/src/contract.rs
contracts/multisig/src/contract/execute.rs
contracts/multisig/src/contract/query.rs
contracts/multisig/src/error.rs
contracts/multisig/src/state.rs
contracts/multisig/src/test/common.rs

https://axelarnetwork.atlassian.net/browse/AXE-2638

feat(multisig): prevent duplicate public key registration

---

Cargo.lock
ampd/Cargo.toml

fix(cargo): avoid linking libssl

---

Cargo.lock
contracts/service-registry/Cargo.toml
contracts/service-registry/src/lib.rs
contracts/service-registry/tests/test_utils/mod.rs
contracts/service-registry/tests/tests.rs

refactor: service registry tests

---

.github/workflows/basic.yaml
.github/workflows/codecov.yaml
Cargo.toml

fix(optimizer): revert rust version to 1.73

---

.github/CODEOWNERS
.github/workflows/build-ampd-main.yaml
.github/workflows/build-ampd-release.yaml

chore(infra): add a seed job for building releases for ampd and fix naming for building main branch ecr image

---

doc/src/contracts/service_registry.md

docs: service-registry-doc

---

Cargo.lock
packages/connection-router-api/Cargo.toml
packages/connection-router-api/src/error.rs
packages/connection-router-api/src/lib.rs
packages/connection-router-api/src/msg.rs
packages/connection-router-api/src/primitives.rs
packages/gateway-api/src/msg.rs

refactor(connection-router-api): replace the code with the latest

---

.github/workflows/build-ampd-release.yaml

fix(infra): differentiate between tags and semvers

---

contracts/connection-router/tests/mock.rs
contracts/gateway/src/contract.rs
contracts/gateway/tests/contract.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/test/mocks/gateway.rs
integration-tests/tests/test_utils/mod.rs
packages/gateway-api/src/msg.rs

refactor: change gateway get messages query name

---

doc/src/contracts/gateway.md

[AXE-3290]
[AXE-3290]: https://axelarnetwork.atlassian.net/browse/AXE-3290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: write gateway.md

---

contracts/multisig/src/msg.rs
doc/src/contracts/multisig.md

Document calling requirements for `AuthorizeCaller` and `UnauthorizeCaller`
https://axelarnetwork.atlassian.net/browse/AXE-3278

docs(multisig): document calling requirements

---

contracts/service-registry/src/contract.rs
contracts/service-registry/src/error.rs
contracts/service-registry/tests/tests.rs
integration-tests/src/contract.rs

get_active_workers returns an error now when the number of active workers is less than the minimum required by the service.
https://axelarnetwork.atlassian.net/browse/AXE-3319

fix(service_registry)!: correctly handle minimum workerset size

---

ampd/src/evm/finalizer.rs

refactor: change ampd finalizer variant names

---

ampd/Dockerfile

fix(ampd): bump rust version in ampd dockerfile

---

Cargo.lock
Cargo.toml
contracts/monitoring/.cargo/config
contracts/monitoring/Cargo.toml
contracts/monitoring/src/bin/schema.rs
contracts/monitoring/src/contract.rs
contracts/monitoring/src/lib.rs
contracts/monitoring/src/msg.rs
contracts/monitoring/src/query.rs

feat: add base structure of monitoring contract

---

contracts/rewards/src/contract.rs
contracts/rewards/src/contract/execute.rs
contracts/rewards/src/contract/query.rs
contracts/rewards/src/state.rs

https://axelarnetwork.atlassian.net/browse/AXE-3515

refactor(rewards): remove `Store` and `Contract` abstractions

---

.github/workflows/release.yaml

chore: include monitoring contract into release pipeline

---

contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/error.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/query.rs
contracts/voting-verifier/src/state.rs
integration-tests/src/voting_verifier_contract.rs
integration-tests/tests/test_utils/mod.rs

https://axelarnetwork.atlassian.net/browse/AXE-3627

feat(minor-voting-verifier)!: allow dynamic updates of voting threshold

---

contracts/service-registry/src/contract.rs

fix(patch-service-registry): pass params in correct order

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/msg.rs

https://axelarnetwork.atlassian.net/browse/AXE-3788
https://axelarnetwork.atlassian.net/browse/AXE-3787

feat(multisig-prover): allow governance to update workerset and document instantiation msg parameters

---

Cargo.lock
contracts/monitoring/Cargo.toml
contracts/monitoring/src/contract.rs
contracts/monitoring/src/error.rs
contracts/monitoring/src/execute.rs
contracts/monitoring/src/msg.rs
contracts/monitoring/src/query.rs
contracts/monitoring/src/state.rs
contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/test/mocks/mod.rs
contracts/multisig-prover/src/test/mocks/monitoring.rs
contracts/multisig-prover/src/test/multicontract.rs
integration-tests/src/multisig_prover_contract.rs
integration-tests/tests/test_utils/mod.rs
integration-tests/tests/update_worker_set.rs

feat(minor-monitoring)!: register active worker set with monitoring

---

Cargo.lock
packages/axelar-wasm-std/Cargo.toml
packages/axelar-wasm-std/src/msg_id/base_58_event_index.rs
packages/axelar-wasm-std/src/msg_id/mod.rs
packages/axelar-wasm-std/src/msg_id/tx_hash_event_index.rs

https://axelarnetwork.atlassian.net/browse/AXE-3720

feat(axelar-wasm-std): implement sui message id trait

---

contracts/voting-verifier/src/msg.rs

docs(voting-verifier): add instantiate msg field comments

---

contracts/gateway/src/msg.rs

https://axelarnetwork.atlassian.net/browse/AXE-3790

docs(gateway): add `InstantiateMsg` field comments

---

ampd/src/commands/mod.rs

fix(ampd): broadcaster init in commands mod

---

doc/src/SUMMARY.md

docs: fix router mdbook link break

---

Cargo.lock
ampd/src/handlers/evm_verify_msg.rs
ampd/src/handlers/evm_verify_worker_set.rs
ampd/src/handlers/sui_verify_worker_set.rs
contracts/nexus-gateway/src/nexus.rs
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/query.rs
contracts/voting-verifier/src/state.rs
integration-tests/Cargo.toml
integration-tests/src/voting_verifier_contract.rs
integration-tests/tests/test_utils/mod.rs
packages/axelar-wasm-std/src/msg_id/base_58_event_index.rs
packages/axelar-wasm-std/src/msg_id/tx_hash_event_index.rs

https://axelarnetwork.atlassian.net/browse/AXE-3836
deployment script change: https://github.com/axelarnetwork/axelar-contract-deployments/pull/219

feat(minor-voting-verifier)!: verify msg ids

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/encoding/abi2/execute_data.rs
contracts/multisig-prover/src/encoding/abi2/mod.rs
contracts/multisig-prover/src/error.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/payload.rs
contracts/multisig-prover/src/query.rs
contracts/multisig-prover/src/state.rs

feat(minor-multisig-prover): encode approve messages for verifiers to sign

---

Cargo.lock
Cargo.toml
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/lib.rs
contracts/voting-verifier/src/migrate.rs
contracts/voting-verifier/src/msg.rs

https://axelarnetwork.atlassian.net/browse/AXE-3938

feat(minor-voting-verifier)!: add migrate endpoint to update gateway address

---

ampd/Dockerfile

chore(infra): add cmake to dockerfile for ampd

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/msg.rs

https://axelarnetwork.atlassian.net/browse/AXE-3786

feat(minor-multisig-prover): allow governance to update admin

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/msg.rs
contracts/multisig-prover/src/query.rs

https://axelarnetwork.atlassian.net/browse/AXE-3686

feat(minor-multisig-prover)!: getWorkerSet returns Option

---

ampd/src/evm/verifier.rs
contracts/coordinator/src/contract.rs
contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/encoding/abi/mod.rs
contracts/multisig-prover/src/test/test_data.rs
contracts/multisig-prover/src/test/test_utils.rs
contracts/multisig/src/msg.rs
contracts/multisig/src/multisig.rs
contracts/multisig/src/signing.rs
contracts/multisig/src/test/common.rs
contracts/multisig/src/worker_set.rs
contracts/service-registry/src/state.rs
contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/query.rs
integration-tests/tests/test_utils/mod.rs
packages/axelar-wasm-std/src/nonempty/uint.rs
packages/axelar-wasm-std/src/operators.rs
packages/axelar-wasm-std/src/snapshot.rs
packages/axelar-wasm-std/src/voting.rs
packages/evm-gateway/src/lib.rs

refactor: change verifier weight and threshold to Uint128

---

contracts/gateway/src/contract/execute.rs
contracts/gateway/tests/contract.rs
contracts/gateway/tests/test_route_incoming.json
contracts/gateway/tests/test_route_outgoing.json
contracts/gateway/tests/test_verify.json
contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/execute.rs
contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/query.rs
packages/axelar-wasm-std/src/verification.rs

refactor(minor): rename VerificationStatus cases for better clarity

---

contracts/coordinator/src/contract.rs
contracts/gateway/src/contract.rs
contracts/multisig-prover/src/contract.rs
contracts/multisig/src/contract.rs
contracts/nexus-gateway/src/contract.rs
contracts/rewards/src/contract.rs
contracts/router/src/contract.rs
contracts/service-registry/src/contract.rs
contracts/voting-verifier/src/contract.rs

https://axelarnetwork.atlassian.net/browse/AXE-4049

refactor: update `CONTRACT_NAME` to get value from crate package

---

ampd/src/commands/bond_worker.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/test/test_utils.rs
contracts/service-registry/src/contract.rs
contracts/service-registry/src/contract/execute.rs
contracts/service-registry/src/contract/query.rs
contracts/service-registry/src/error.rs
contracts/service-registry/src/msg.rs
contracts/service-registry/src/state.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/execute.rs
integration-tests/tests/bond_unbond.rs
integration-tests/tests/chain_freeze_unfreeze.rs
integration-tests/tests/message_routing.rs
integration-tests/tests/test_utils/mod.rs
integration-tests/tests/update_worker_set.rs

refactor(minor-service-registry): rename worker to verifier

---

contracts/multisig-prover/src/encoding/abi/execute_data.rs
contracts/multisig-prover/src/encoding/abi/mod.rs
contracts/multisig-prover/src/encoding/mod.rs
contracts/multisig-prover/src/execute.rs
contracts/multisig-prover/src/test/test_data.rs
contracts/multisig-prover/src/test/test_utils.rs
contracts/multisig-prover/src/types.rs
doc/src/contracts/multisig_prover.md

https://axelarnetwork.atlassian.net/browse/AXE-4060

refactor(multisig-prover): rename worker to verifier

---

contracts/multisig/src/contract/query.rs
doc/src/contracts/multisig.md

https://axelarnetwork.atlassian.net/browse/AXE-4059

refactor(multisig): rename worker to verifier

---

contracts/service-registry/src/migrations/v_0_3.rs
contracts/service-registry/src/state.rs

refactor(service-registry): remove CHAINS_PER_VERIFIER

---

ampd/Cargo.toml
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/state.rs

refactor(voting-verifier): rename to verifier set in state.rs

---

ampd/src/broadcaster.rs
ampd/src/commands/mod.rs
ampd/src/commands/register_public_key.rs
ampd/src/handlers/multisig.rs
ampd/src/lib.rs
ampd/src/tofnd/grpc.rs

refactor(ampd): merge tofnd MultisigClient and SharableEcdsaClient

---

ampd/proto/ampd.proto
ampd/proto/tofnd/common.proto
ampd/proto/tofnd/multisig.proto
ampd/src/broadcaster.rs
ampd/src/commands/mod.rs
ampd/src/commands/register_public_key.rs
ampd/src/grpc/ampd.rs
ampd/src/grpc/crypto.rs
ampd/src/grpc/mod.rs
ampd/src/handlers/multisig.rs
ampd/src/lib.rs
ampd/src/tofnd/grpc.rs
ampd/src/tofnd/mod.rs

feat(ampd): add tofnd grpc server support

---

contracts/multisig-prover/src/contract.rs
contracts/multisig-prover/src/msg.rs
contracts/multisig-prover/src/query.rs
integration-tests/tests/test_utils/mod.rs

feat(minor-multisig-prover): next verifier set query

---

Cargo.lock
Cargo.toml
ampd/Cargo.toml

chore: update dependencies

---

README.md

docs: update compatibility matrix

---

ampd/Cargo.toml

fix(ampd): enable derive feature for der crate

---

contracts/gateway/tests/test_route_incoming.json
contracts/gateway/tests/test_route_outgoing.json
contracts/gateway/tests/test_verify.json
packages/router-api/src/primitives.rs

fix(minor-router): use singular form for address in event attribute

---

contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/execute.rs
contracts/voting-verifier/src/query.rs
packages/axelar-wasm-std/src/voting.rs

https://axelarnetwork.atlassian.net/browse/AXE-4319

feat(minor-voting-verifier): allow restarting expired polls

---

contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/execute.rs

https://axelarnetwork.atlassian.net/browse/AXE-4367

feat(minor-voting-verifier): add poll id to quorum reached event

---

Cargo.lock
Cargo.toml
README.md
ampd/Cargo.toml
ampd/src/tofnd/grpc.rs
contracts/coordinator/Cargo.toml
integration-tests/Cargo.toml

[AXE-4389]
[AXE-4389]: https://axelarnetwork.atlassian.net/browse/AXE-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(minor-ampd): support tofnd v1 ed25519 sig encoding

---

contracts/coordinator/src/contract.rs
contracts/coordinator/src/contract/migrations/mod.rs
contracts/coordinator/src/contract/migrations/v0_2_0.rs
contracts/coordinator/src/state.rs

https://axelarnetwork.atlassian.net/browse/AXE-4379

feat(coordinator): add registered provers migration to new state

---

ampd/src/sui/verifier.rs
contracts/multisig/src/key.rs
contracts/multisig/src/verifier_set.rs

Some example of the SignersRotated event https://suiscan.xyz/testnet/tx/A1bhRKCobvJx5yYPpCKzrEnWHgh1mz57kPHV5SAy23MY

feat(ampd): sui verify verifier set confirmation

---

Cargo.lock
contracts/gateway/src/contract.rs
packages/gateway-api/Cargo.toml
packages/gateway-api/src/msg.rs

feat(gateway): add permission control to gateway

---

integration-tests/src/rewards_contract.rs

refactor(minor-integration-tests): use rewards query for contract wrapper creation

---

contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/query.rs
contracts/voting-verifier/src/state.rs

feat(minor-voting-verifier): query poll by id

---

doc/src/SUMMARY.md

docs: add bullet points to all chapters of SUMMARY.md

---

contracts/gateway/src/state.rs
contracts/router/src/contract.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/contract/query.rs
contracts/voting-verifier/src/events.rs
packages/router-api/src/primitives.rs

[AXE-4518]
[AXE-4518]: https://axelarnetwork.atlassian.net/browse/AXE-4518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(minor-router): unambiguous message hash computation

---

ampd/src/event_sub.rs
ampd/src/tm_client.rs

https://axelarnetwork.atlassian.net/browse/AXE-4527

feat(ampd): retry fetching block height

---

ampd/Dockerfile

fix(ampd): copy ITS folder to docker image for ampd build

---

.github/workflows/build-contracts-and-push-to-r2.yaml

ci: update description for contract build action to include tags

---

Cargo.lock
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/contract/execute.rs
contracts/voting-verifier/src/contract/migrations/v0_5_0.rs
contracts/voting-verifier/src/error.rs
contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/msg.rs
contracts/voting-verifier/src/state.rs
integration-tests/src/voting_verifier_contract.rs
integration-tests/tests/chain_freeze_unfreeze.rs
integration-tests/tests/message_routing.rs
packages/axelar-wasm-std/Cargo.toml
packages/axelar-wasm-std/src/address_format.rs
packages/axelar-wasm-std/src/lib.rs

feat(minor-voting-verifier): validate source address

---

.github/workflows/build-contracts-and-push-to-r2.yaml

fix(ci): add extra condition for get-tag step to also check input branch

---

Cargo.lock
contracts/gateway/Cargo.toml
contracts/gateway/src/contract.rs
contracts/gateway/src/contract/execute.rs
contracts/gateway/tests/contract.rs

fix(minor-gateway): do not override outgoing messages

---

.github/workflows/release.yaml

chore: add major/minor commit message signifiers for release action

---

.github/workflows/build-contracts-and-push-to-r2.yaml

refactor(ci): rename r2 pre-releases folder to cosmwasm

---

.github/workflows/build-ampd-release.yaml

feat(ampd): upload ampd releases to r2

---

.github/actions/release/action.yaml
.github/workflows/build-ampd-release.yaml
.github/workflows/build-contracts-and-push-to-r2.yaml
.github/workflows/release.yaml

fix(ci): auto trigger build action for new tags with custom token

---

Cargo.toml
ampd/Cargo.toml
contracts/coordinator/Cargo.toml
contracts/gateway/Cargo.toml
contracts/multisig-prover/Cargo.toml
contracts/multisig/Cargo.toml
contracts/nexus-gateway/Cargo.toml
contracts/rewards/Cargo.toml
contracts/router/Cargo.toml
contracts/service-registry/Cargo.toml
contracts/voting-verifier/Cargo.toml
integration-tests/Cargo.toml
interchain-token-service/Cargo.toml
packages/axelar-wasm-std-derive/Cargo.toml
packages/axelar-wasm-std/Cargo.toml
packages/client/Cargo.toml
packages/events-derive/Cargo.toml
packages/events/Cargo.toml
packages/evm-gateway/Cargo.toml
packages/gateway-api/Cargo.toml
packages/msgs-derive/Cargo.toml
packages/report/Cargo.toml
packages/router-api/Cargo.toml
packages/signature-verifier-api/Cargo.toml

[AXE-4624]
[AXE-4624]: https://axelarnetwork.atlassian.net/browse/AXE-4624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use workspace rust edition in crates

---

ampd/Dockerfile

fix(ampd): copy external-gateways folder to dockerfile

---

Cargo.lock
contracts/axelarnet-gateway/src/client.rs
contracts/axelarnet-gateway/src/contract.rs
contracts/axelarnet-gateway/src/contract/execute.rs
contracts/axelarnet-gateway/src/lib.rs
contracts/axelarnet-gateway/src/msg.rs
contracts/nexus-gateway/Cargo.toml
contracts/nexus-gateway/src/contract.rs
contracts/nexus-gateway/src/contract/execute.rs
contracts/nexus-gateway/src/error.rs
contracts/nexus-gateway/src/msg.rs
contracts/nexus-gateway/src/nexus.rs
contracts/nexus-gateway/src/state.rs

feat(nexus-gateway)!: call contract with token

---

Cargo.lock
Cargo.toml
contracts/axelarnet-gateway/Cargo.toml
contracts/axelarnet-gateway/src/contract.rs
contracts/axelarnet-gateway/src/lib.rs
contracts/axelarnet-gateway/tests/execute.rs
contracts/axelarnet-gateway/tests/instantiate.rs
contracts/axelarnet-gateway/tests/query.rs
packages/axelar-wasm-std/src/error.rs

[AXE-4762]
[AXE-4762]: https://axelarnetwork.atlassian.net/browse/AXE-4762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add assert_err_contains and assert_ok macros

---

Cargo.lock
contracts/voting-verifier/Cargo.toml
contracts/voting-verifier/src/client.rs
contracts/voting-verifier/src/contract.rs
contracts/voting-verifier/src/error.rs
integration-tests/src/voting_verifier_contract.rs
integration-tests/tests/test_utils/mod.rs

[AXE-4798]
[AXE-4798]: https://axelarnetwork.atlassian.net/browse/AXE-4798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(voting-verifier): validate source gateway address format

---

contracts/service-registry/src/contract.rs

* improve the error message returned from register chain support
https://axelarnetwork.atlassian.net/browse/AXE-5102

fix(minor-service-registry): improve error message

---

contracts/service-registry/src/msg.rs

refactor(service-registry): remove unused MigrationMsg

---

ampd/Dockerfile

fix(ampd): add ca-certificates to image

---

ampd/src/stellar/http_client.rs

chore(ampd): improve Stellar client logging on transaction query failure

---

Cargo.lock
Cargo.toml
contracts/router/Cargo.toml

chore: release router 1.0.1

---

ampd/src/stellar/verifier.rs

[AXE-6139](https://axelarnetwork.atlassian.net/browse/AXE-6139)
[AXE-6139]: https://axelarnetwork.atlassian.net/browse/AXE-6139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(minor-ampd): update stellar event names

---

contracts/interchain-token-service/src/contract.rs
contracts/interchain-token-service/src/contract/execute.rs
contracts/interchain-token-service/src/events.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/tests/execute.rs

* governance or admin can disable/enable execution of its messages
https://axelarnetwork.atlassian.net/browse/AXE-6233

feat(minor-its-hub): add support for global freeze

---

contracts/interchain-token-service/src/msg.rs

docs: correct spelling mistake

---

contracts/interchain-token-service/src/contract/execute/interceptors.rs
contracts/interchain-token-service/src/contract/execute/mod.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/src/state.rs
contracts/interchain-token-service/tests/execute.rs
contracts/interchain-token-service/tests/utils/execute.rs

* use destination chain config for decimal truncation

feat(minor-interchain-token-service): fix amount scaling

---

contracts/interchain-token-service/release.toml

fix(interchain-token-service): enable ITS release

---

Cargo.lock
ampd/Cargo.toml

Sui rpc changed event serialization from base58 to base64, need bump up deps to deserialize events

chore(ampd): sui deps update

---

contracts/router/src/contract.rs
contracts/router/src/contract/execute.rs

feat(router): use core chain query to determine if route to axelarnet gateway

---

Cargo.lock
ampd/Cargo.toml
packages/events/Cargo.toml

chore: update tendermint rs

---

contracts/voting-verifier/src/contract/execute.rs
contracts/voting-verifier/src/events.rs

feat(minor-voting-verifier): add votes to the Voted event

---

Cargo.lock
Cargo.toml
packages/axelar-wasm-std-derive/Cargo.toml
packages/axelar-wasm-std-derive/src/lib.rs

suggestions for #734

---

.github/workflows/build-contracts-and-push-to-r2.yaml

fix(ci): use default snake case naming for cosmwasm releases

---

Cargo.lock
contracts/router/Cargo.toml
contracts/router/src/contract.rs
contracts/router/src/testdata/chain_info_fails_on_unregistered_chain.golden

Ensure that the error string that axelarons depends on doesn't change unexpectedly

test(router): add golden test for chain not found failure

---

contracts/voting-verifier/src/events.rs
contracts/voting-verifier/src/testdata/events_should_not_change.golden

refactor(voting-verifier-minor): improve event tests

---

contracts/interchain-token-service/src/contract/execute/interceptors.rs
contracts/interchain-token-service/src/contract/execute/mod.rs

allow reregistration of custom token with same decimals

fix(minor-interchain-token-service): custom token reregistration

---

contracts/interchain-token-service/src/contract.rs
contracts/interchain-token-service/src/contract/query.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/src/state.rs
contracts/interchain-token-service/tests/execute.rs
contracts/interchain-token-service/tests/query.rs
contracts/interchain-token-service/tests/utils/query.rs

feat(minor-interchain-token-service): extend its address query with chain config info

---

contracts/interchain-token-service/src/contract.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/tests/utils/query.rs

fix(interchain-token-service): change `ITSChain` query case to `ItsChain`

---

contracts/interchain-token-service/src/contract.rs
contracts/interchain-token-service/src/contract/query.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/tests/query.rs
contracts/interchain-token-service/tests/utils/execute.rs
contracts/interchain-token-service/tests/utils/query.rs

feat(minor-interchain-token-service): contract status query message

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add convention checklist to the PR template

---

ampd/Dockerfile

fix(ampd): add ampd handlers copy stage to Dockerfile

---

contracts/interchain-token-service/src/contract.rs
contracts/interchain-token-service/src/contract/execute/mod.rs
contracts/interchain-token-service/src/contract/migrations/mod.rs
contracts/interchain-token-service/src/contract/migrations/v1_1_0.rs
contracts/interchain-token-service/src/msg.rs
contracts/interchain-token-service/src/state.rs
contracts/interchain-token-service/tests/execute.rs
contracts/interchain-token-service/tests/instantiate.rs
contracts/interchain-token-service/tests/utils/instantiate.rs
contracts/interchain-token-service/tests/utils/params.rs

* operator can call register_p2p_token and modify_supply
https://axelarnetwork.atlassian.net/browse/AXE-8493

feat(minor-interchain-token-service): add operator role

---

.github/workflows/ampd-handlers-docker-ecr.yaml
Cargo.lock
ampd-handlers/Cargo.toml
ampd-handlers/Dockerfile
ampd-handlers/src/main.rs

feat(ampd-handlers): base handler client connection and image creation process

---

.github/workflows/codecov.yaml

This should fix rate limits on PRs coming from forks
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e526867c91905d03a6a8b1a41110b/packages/axelar-wasm-std-derive/src/lib.rs#L160): Event …

ci: upgrade codecov to v4

---

.github/workflows/ampd-handlers-docker-ecr.yaml
.github/workflows/build-ampd-main.yaml

ci: optimize docker build process

---

Cargo.toml
ampd/Cargo.toml
contracts/axelarnet-gateway/Cargo.toml
contracts/coordinator/Cargo.toml
contracts/gateway/Cargo.toml
contracts/interchain-token-service/Cargo.toml
contracts/multisig-prover/Cargo.toml
contracts/multisig/Cargo.toml
contracts/rewards/Cargo.toml
contracts/router/Cargo.toml
contracts/service-registry/Cargo.toml
contracts/voting-verifier/Cargo.toml
external-gateways/stellar/Cargo.toml
integration-tests/Cargo.toml
packages/ampd-sdk/Cargo.toml
packages/ampd-sdk/src/grpc/client.rs
packages/axelar-wasm-std/Cargo.toml
packages/sui-gateway/Cargo.toml

feat(ampd-sdk): implement blockchain broadcast

---

contracts/coordinator/src/contract.rs

refactor(coordinator): remove top-level execute and query errors in coordinator

---

contracts/coordinator/src/client.rs
contracts/coordinator/src/contract.rs
contracts/coordinator/src/contract/execute.rs
contracts/coordinator/src/contract/migrations/mod.rs
contracts/coordinator/src/contract/query.rs
contracts/coordinator/src/msg.rs
contracts/coordinator/src/state.rs
integration-tests/src/coordinator_contract.rs

refactor(major-coordinator): resolve cyclic instantiation dependency with router

---

ampd/Dockerfile

- added curl and wget to ampd's Dockerfile for testing purposes
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e526867c91905d03a6a8b1a41110b/packages/axelar-wasm-std-derive/src/lib.rs#L160): …

chore(ampd): added curl and wget to ampd's Dockerfile

---

packages/ampd-sdk/src/grpc/client.rs

feat(ampd-sdk): client crypto service sign and key methods

---

contracts/interchain-token-service/CHANGELOG.md

docs(interchain-token-service): add ITS hub changelog

---

ampd/src/broadcast/mod.rs
ampd/src/event_processor.rs
ampd/src/grpc/blockchain_service.rs

chore(ampd): deserialize cosmrs message values
