axelarnetwork/axelar-amplifier

- Cargo.lock
- Cargo.toml
- ampd/Cargo.toml
- ampd/src/config.rs
- ampd/src/evm/mod.rs
- ampd/src/handlers/config.rs
- ampd/src/handlers/mod.rs
- ampd/src/handlers/multisig.rs
- ampd/src/lib.rs
- ampd/src/tofnd/grpc.rs
> refactor: ampd configs should contain a Vec of handler configs

- .github/workflows/conventional-commits.yml
https://github.com/axelarnetwork/axelar-amplifier/actions/runs/6175533191/job/16762609790
conventional commits action can only run on pull requests.
> chore: revert conventional commits action running on push

- Cargo.lock
- Cargo.toml
- packages/axelar-wasm-std-derive/Cargo.toml
- packages/axelar-wasm-std-derive/src/lib.rs
- packages/axelar-wasm-std-derive/tests/derive.rs
- packages/axelar-wasm-std/Cargo.toml
- packages/axelar-wasm-std/src/error.rs
- packages/axelar-wasm-std/src/lib.rs
- packages/report/src/loggable.rs
In preparation to introduce error-stack into the contracts, we need a top level error that cosmwasm is able to return and which accepts both cosmwasm StdErrors and error stack reports. In order to make implementation for contract specific errors easier, a derive macro is provided that implements the From/Into trait.
The changes to LoggableError are simple restructuring the file
> feat: add generalized contract error with derive macro

- contracts/gateway/src/contract.rs
- contracts/gateway/src/contract/execute.rs
to make it easier to write isolated unit tests I'm extracting the module into its own file
> refactor: extract gateway execute module

- contracts/multisig-prover/src/contract.rs
- contracts/multisig-prover/src/error.rs
- contracts/multisig-prover/src/execute.rs
`construct_proof` updates the worker_set automatically if it needs to be updated. two test cases were added for checking if the worker set was updated, and for checking that it causes an error if there is no worker set initially.
`cargo test` test cases all pass
> feat: let construct_proof update worker_set

- contracts/connection-router/src/state.rs
- contracts/multisig-prover/src/test/mocks/voting_verifier.rs
- contracts/nexus-gateway/src/error.rs
- contracts/nexus-gateway/src/nexus.rs
- contracts/voting-verifier/src/error.rs
- contracts/voting-verifier/src/events.rs
- contracts/voting-verifier/src/execute.rs
- contracts/voting-verifier/src/msg.rs
- contracts/voting-verifier/tests/tests.rs
- packages/axelar-wasm-std/src/nonempty/string.rs
Any way I tried to cut it, it's impossible to move to using the apis defined in #146 without massive changes. So instead, the strategy will be to modify the data structs in connection router step by step until they look exactly like #146 and then have a single massive PR that only changes the dependency path in all affected files
> refactor: eliminate MessageId struct

- packages/axelar-wasm-std/src/voting.rs
Prerequisite to integrate voting with rewards. Before this change a poll is completed only when the poll is expired or when everyone voted. In order to integrate with rewards, it should be allowed to be completed when the quorum is satisfied to allow for a grace period between expiration and poll completion
https://axelarnetwork.atlassian.net/browse/AXE-2201
> feat(voting-verifier): allow end poll to complete before expiration if a result has reached quorum

- ampd/Dockerfile
[AXE-2450]
1. Place your `config.toml` file in the `ampd` folder.
2. Build the docker container:
`docker build -t ampd -f ampd/Dockerfile .`
3. Run the docker container with arguments (example usage)
docker run -v $(pwd)/ampd:/usr/local/bin/config -it ampd -c config/config.toml`
[AXE-2450]: https://axelarnetwork.atlassian.net/browse/AXE-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ampd): add support for command line arguments

- Cargo.lock
- contracts/voting-verifier/Cargo.toml
- contracts/voting-verifier/src/contract.rs
- contracts/voting-verifier/src/execute.rs
- contracts/voting-verifier/src/msg.rs
- contracts/voting-verifier/src/state.rs
- contracts/voting-verifier/tests/mock.rs
- contracts/voting-verifier/tests/tests.rs
- packages/axelar-wasm-std/src/voting.rs
Calls reward contract to record participation when casting a vote. Rewards gets distributed after poll completion to all participants that voted for the consensus result
https://axelarnetwork.atlassian.net/browse/AXE-2411
> feat(voting-verifier): integrate voting with rewards contract

- packages/axelar-wasm-std/src/nonempty/uint.rs
[AXE-2574]
Adds test cases to `uint.rs` that codecov identified were missing.
`cargo test` passes
[AXE-2574]: https://axelarnetwork.atlassian.net/browse/AXE-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: add additional test cases to uint.rs

- packages/axelar-wasm-std/src/nonempty/uint.rs
- packages/axelar-wasm-std/src/snapshot.rs
[AXE-2636]
Uses AsRef for Uint256
`cargo test` passes
[AXE-2636]: https://axelarnetwork.atlassian.net/browse/AXE-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: implement AsRef in uint.rs

- contracts/nexus-gateway/src/contract.rs
- contracts/nexus-gateway/src/contract/execute.rs
- contracts/nexus-gateway/src/msg.rs
> fix(nexus-gateway): remove untagged and split RouteMessages into two separate messages

- integration-tests/tests/update_worker_set.rs
Adds an integration test for automatically updating worker set if a newer one is found during proof construction.
> test(multisig-prover): add integration test for automatically updating worker set

- Cargo.lock
- ampd/src/handlers/evm_verify_msg.rs
- ampd/src/handlers/evm_verify_worker_set.rs
- ampd/src/handlers/multisig.rs
- ampd/src/handlers/sui_verify_msg.rs
- ampd/src/handlers/sui_verify_worker_set.rs
- packages/events/Cargo.toml
- packages/events/src/event.rs
The handlers currently return an error when encountering an event with the same event_type as what they are looking for, but with different fields. This can happen due to contract upgrades, but also if any random contract emits an event with the same event_type as the event the handler cares about. This can cause either crashing the process, or unnecessary retries (and waiting).
This PR makes a change so that the handlers first check the "_contract_address" field of the event, and simply skip the event (returning `Ok(())` ) if the address doesn't match the contract address for which the handler is configured to handle events.
https://axelarnetwork.atlassian.net/browse/AXE-3080
> fix(ampd): skip events from unknown contracts

- .github/workflows/basic.yaml
- .github/workflows/codecov.yaml
Use faster blacksmith runners for gh actions. More info here https://github.com/BlacksmithOSSTests/axelar-amplifier/pull/4
See the following for comparison
GH runners, `~8.5 mins`: https://github.com/axelarnetwork/axelar-amplifier/actions/runs/7903746303/job/21572373695
Blacksmith runners `~3.5 mins` but still cheaper than github 8-core cpu: https://github.com/axelarnetwork/axelar-amplifier/actions/runs/7906836074/job/21583013684?pr=271
See blacksmith pricing [here](https://docs.blacksmith.sh/runners/pricing). First `3000` mins/month are free.
- the 8vCPU run is ~38% [faster](https://github.com/BlacksmithOSSTests/axelar-amplifier/actions/runs/7892299883/job/21538883237?pr=1), and ~70% cheaper
- the 16vCPU runs are ~50% [faster](https://github.com/axelarnetwork/axelar-amplifier/actions/runs …
> ci: use blacksmith runners for gh actions

- Cargo.lock
- contracts/multisig/Cargo.toml
- contracts/multisig/src/ed25519.rs
- contracts/multisig/src/error.rs
- contracts/multisig/src/key.rs
- contracts/multisig/src/state.rs
https://axelarnetwork.atlassian.net/browse/AXE-3263
> fix(multisig): normalize compressed and uncompressed public keys for proper duplicate check

- contracts/multisig/src/ed25519.rs
- contracts/multisig/src/key.rs
- contracts/multisig/src/secp256k1.rs
- make sure parameters for ecdsa and ed25519 verifying functions are the same
- ensure they throw an error instead of truncating to required byte length
https://axelarnetwork.atlassian.net/browse/AXE-3275
> refactor(multisig): adjust diverging behavior in signature verification

- contracts/connection-router/src/contract/execute.rs
- contracts/connection-router/src/events.rs
- doc/src/contracts/connection_router.md
`unfreeze_chain()` was emitting `ChainFreeze` event instead of `ChainUnfreeze`. Fixed that and also added the gateway direction to these events attributes
https://axelarnetwork.atlassian.net/browse/AXE-3418
> fix(minor-connection-router)!: emit correct event when unfreezing chain and add freeze/unfreeze direction to events

- .github/workflows/basic.yaml
- contracts/gateway/src/contract.rs
- contracts/gateway/src/contract/query.rs
- contracts/gateway/tests/contract.rs
Expected behaviour for the query is to return an error if any of the message IDs cannot be found, but instead it just dropped those IDs from the response
AXE-3579
> fix: get_outgoing_messages in the gateway returns error if msgs are missing

- Cargo.lock
- contracts/multisig/Cargo.toml
- contracts/multisig/src/key.rs
There is a warning in function `ed25519_dalek::VerifyingKey::from_bytes` that says:
> The caller is responsible for ensuring that the bytes passed into this method actually represent a curve25519_dalek::curve::CompressedEdwardsY and that said compressed point is actually a point on the curve.
However upon further inspection it doesn't seem to be possible to generate a `VerifyingKey` that represents an invalid point in the curve using `from_bytes` function, because it will throw an error when trying to decompress into an invalid point.
This PR adds unit tests to ensure our `validate_and_normalize_public_key` doesn't allow the creation of public keys that represents invalid points in the curves
https://axelarnetwork.atlassian.net/browse/AXE-3312
> chore(multisig): test PublicKey is validated to represent a valid point in the curve

- contracts/service-registry/src/contract.rs
- contracts/service-registry/src/error.rs
- contracts/service-registry/src/msg.rs
- contracts/service-registry/src/state.rs
- contracts/service-registry/tests/tests.rs
Governance can jail workers. A jailed worker cannot unbond or claim stake.
> feat(service-registry): jail worker

- Cargo.lock
- ampd/Cargo.toml
- ampd/README.md
- ampd/src/config.rs
- ampd/src/health_check.rs
- ampd/src/lib.rs
- ampd/src/tests/config_template.toml
At [Eiger](https://github.com/eigerco) we are working on the `Axelar Solana` implementation.  During this work, we realised `ampd` doesn't have a defined way to check the `liveness` of the process from an external perspective. This is specially useful when deploying workloads in i.e Kubernetes, as the cluster can query the process in order to check if its alive or not.
This is a PR proposal for adding an `HTTP` `/status` endpoint to the `ampd` process, that can be used by external systems to determine the `liveness` of the process.
Closes https://github.com/eigerco/axelar-amplifier/issues/12
1. Start the `ampd` server.
2. ```bash
$ curl localhost:3000/status
```
```bash
$ cd ampd && cargo test
```
Once `ampd` starts its activity, an HTTP request to the `/status` endpoint should return a …
> feat: add initial healthcheck endpoint (ampd)

- contracts/nexus-gateway/src/contract/execute.rs
- contracts/nexus-gateway/src/error.rs
- contracts/nexus-gateway/src/nexus.rs
- packages/axelar-wasm-std/src/msg_id/tx_hash_event_index.rs
Nexus gateway was still using colon, instead of dash in message ids, and was not prefixing with 0x.
https://axelarnetwork.atlassian.net/browse/AXE-3719
> fix(minor-nexus-gateway)!: make msg id consistent with evm chains

- ampd/src/broadcaster.rs
> fix(ampd): broadcast client builder should not require the acc sequence

- Cargo.lock
- ampd/Cargo.toml
- ampd/src/broadcaster.rs
- ampd/src/broadcaster/tx.rs
- ampd/src/commands/mod.rs
- ampd/src/lib.rs
The typed-builder crate is compile-time safe instead of just returning an error at runtime if the build fails
> refactor(ampd): use typed-builder instead of derive_builder

- ampd/src/event_sub.rs
- ampd/src/lib.rs
> refactor(ampd): change the event_sub so that subscribers can be added at runtime

- Cargo.lock
- packages/evm-gateway/Cargo.toml
https://axelarnetwork.atlassian.net/browse/AXE-4061
Used zip crate version was yanked from crates.io: https://crates.io/crates/zip/versions, so this fix increases the version to one that is available
> fix(evm-gateway): updated zip crate to a version available in crates.io

- contracts/nexus-gateway/src/nexus.rs
The evm gateway truncates source tx id to 32 bytes. Putting the entire message id in this field is not very useful, since the value gets truncated.
https://axelarnetwork.atlassian.net/browse/AXE-4216
> feat(minor-nexus-gateway): set source tx id 0 when parsing fails

- ampd/src/lib.rs
- ampd/src/queue/queued_broadcaster.rs
> fix(ampd): directly pass interval to queued broadcaster and ignore first tick

- Cargo.lock
- contracts/multisig/Cargo.toml
- contracts/multisig/src/contract.rs
- contracts/multisig/src/contract/execute.rs
- contracts/multisig/src/error.rs
- contracts/multisig/src/events.rs
- contracts/multisig/src/msg.rs
- contracts/multisig/src/state.rs
- contracts/router/src/contract.rs
- contracts/router/src/contract/execute.rs
- contracts/router/src/contract/migrations/v0_3_3.rs
- contracts/router/src/contract/query.rs
- contracts/router/src/state.rs
- integration-tests/src/multisig_contract.rs
- integration-tests/tests/test_utils/mod.rs
- packages/axelar-wasm-std/src/killswitch.rs
- packages/axelar-wasm-std/src/lib.rs
adds a generic killswitch module that can be used by any contract (currently router and multisig)
Followups:
- Allow authorize and unauthorize caller to take a list of addresses
- migration of multisig
- use callback in permission control for start signing session, submit signature, and register verifier set
https://axelarnetwork.atlassian.net/browse/AXE-4359
> feat(minor-multisig)!: add command to disable all signing

- contracts/service-registry/src/state.rs
> refactor(service-registry): remove unused config from state file

- ampd/src/asyncutil/task.rs
- ampd/src/block_height_monitor.rs
- ampd/src/broadcaster/confirm_tx.rs
- ampd/src/commands/mod.rs
- ampd/src/event_sub.rs
- ampd/src/health_check.rs
- ampd/src/lib.rs
- ampd/src/queue/msg_queue.rs
- ampd/src/queue/queued_broadcaster.rs
AXE-4740
AXE-4741
This resolves the deadlock and adds additional logging on task shut down, so it's easier to understand which process is shutting down
> fix(ampd): resolve deadlock between broadcaster and confirmer on shutdown

- ampd/src/commands/register_chain_support.rs
https://axelarnetwork.atlassian.net/browse/AXE-5103
> fix(minor-ampd): reject missing chain in register chain support command

- ampd/src/handlers/stellar_verify_msg.rs
- ampd/src/handlers/stellar_verify_verifier_set.rs
- ampd/src/stellar/verifier.rs
Soroban gateway rotation [event](https://github.com/axelarnetwork/axelar-cgp-soroban/blob/main/contracts/axelar-gateway/src/event.rs#L33)
> fix(ampd): stellar tx receipt query and event check

- Cargo.lock
- ampd/Cargo.toml
- ampd/src/lib.rs
- ampd/src/mvx/proxy.rs
- ampd/src/mvx/verifier.rs
There was a bug in the Rust SDK for MultiversX and some transactions could not be retrieved properly from the blockchain.
> fix(minor-ampd): update MultiversX sdk to fix transaction not being verified bug

- CHANGELOG.md
- Cargo.lock
- ampd/src/evm/verifier.rs
- ampd/src/handlers/evm_verify_msg.rs
- ampd/src/handlers/evm_verify_verifier_set.rs
- ampd/src/handlers/mvx_verify_msg.rs
- ampd/src/handlers/mvx_verify_verifier_set.rs
- ampd/src/handlers/stellar_verify_msg.rs
- ampd/src/handlers/stellar_verify_verifier_set.rs
- ampd/src/handlers/sui_verify_msg.rs
- ampd/src/handlers/sui_verify_verifier_set.rs
- ampd/src/stellar/http_client.rs
- ampd/src/stellar/verifier.rs
- ampd/src/sui/verifier.rs
- contracts/router/src/contract/execute.rs
- contracts/voting-verifier/src/contract.rs
- contracts/voting-verifier/src/contract/execute.rs
- contracts/voting-verifier/src/contract/query.rs
- contracts/voting-verifier/src/events.rs
- packages/axelar-core-std/src/nexus/execute.rs
- packages/axelar-wasm-std/Cargo.toml
- packages/axelar-wasm-std/src/msg_id/base_58_event_index.rs
- packages/axelar-wasm-std/src/msg_id/base_58_solana_event_index.rs
- packages/axelar-wasm-std/src/msg_id/tx_hash_event_index.rs
* This change also affects axelarnet-gateway, voting-verifier, and ampd
* In some cases, ampd will automatically vote NotFound if the u64 overflows u32 (since some RPC interfaces do not allow indexing events via u64)
* Emit message id in poll started event. Ampd parses message id.
* Deprecate emitting tx id and event index in poll started event.
https://axelarnetwork.atlassian.net/browse/AXE-4627
> feat(minor-router)!: change u32 to u64 in message ids

- contracts/interchain-token-service/src/contract.rs
- contracts/interchain-token-service/src/contract/execute.rs
- contracts/interchain-token-service/src/contract/query.rs
- contracts/interchain-token-service/src/msg.rs
- contracts/interchain-token-service/src/state.rs
- contracts/interchain-token-service/tests/execute.rs
* Add support for freezing and unfreezing specific chains
https://axelarnetwork.atlassian.net/browse/AXE-6265
> feat(minor-interchain-token-service): freeze/unfreeze

- contracts/interchain-token-service/src/contract/execute/interceptors.rs
- contracts/interchain-token-service/src/contract/execute/mod.rs
- contracts/interchain-token-service/src/state.rs
* all TokenInstance's now have decimals, since DeployTokenManager is no longer supported
> feat(minor-interchain-token-service): make decimals non optional

- CHANGELOG.md
update the changelog for the coming release. This is the commit we should tag as the github release
> chore: update changelog for v1.3.0

- ampd/README.md
- contracts/multisig-prover/src/contract.rs
- contracts/rewards/src/contract.rs
> fix(ampd): bump ampd patch version

- .github/workflows/basic.yaml
> chore: add flag --no-fail-fast to the gh action so that it reports all failing tests

- Cargo.lock
- packages/axelar-wasm-std-derive/Cargo.toml
- packages/axelar-wasm-std-derive/src/lib.rs
- packages/events-derive/Cargo.toml
- packages/into-inner-derive/Cargo.toml
> feat(minor-axelar-wasm-std-derive): derive macro into_event_derive

- packages/axelar-wasm-std-derive/src/lib.rs
> feat(axelar-wasm-std-derive-minor): add generics support for into-event derive macro

- ampd/src/handlers/multisig.rs
> fix(ampd): multisig handler

- Cargo.lock
- Cargo.toml
- contracts/router/src/contract.rs
- contracts/router/src/contract/migrations/mod.rs
- contracts/router/src/msg.rs
- tools/migration-remover/Cargo.toml
- tools/migration-remover/README.md
- tools/migration-remover/src/main.rs
- tools/migration-remover/src/template.rs
This tool assumes the contrac's migration code follows the same directory structure as the router contract on this PR, i.e. all migration-related code must be inside `src/contract/migrations`
More info in README
How to test:
```
cargo run --bin migration-remover -- -c router
```
https://axelarnetwork.atlassian.net/browse/AXE-7389
> feat: add contracts migration remover tool

- ampd/Dockerfile
> fix: add `tools` dir to ampd Dockerfile

- contracts/axelarnet-gateway/src/contract/query.rs
- contracts/axelarnet-gateway/src/msg.rs
> refactor(minor-axelarnet-gateway): msg and state separation

- contracts/interchain-token-service/src/contract.rs
- contracts/interchain-token-service/src/contract/query.rs
- contracts/interchain-token-service/src/msg.rs
- contracts/interchain-token-service/src/state.rs
- contracts/interchain-token-service/tests/query.rs
- contracts/interchain-token-service/tests/utils/execute.rs
- contracts/interchain-token-service/tests/utils/query.rs
> feat(minor-interchain-token-service): all chains with optional filter query message 

- contracts/interchain-token-service/src/contract.rs
- contracts/interchain-token-service/src/contract/execute/interceptors.rs
- contracts/interchain-token-service/src/contract/execute/mod.rs
- contracts/interchain-token-service/src/contract/query.rs
- contracts/interchain-token-service/src/lib.rs
- contracts/interchain-token-service/src/msg.rs
- contracts/interchain-token-service/src/shared.rs
- contracts/interchain-token-service/src/state.rs
- contracts/interchain-token-service/tests/execute.rs
- contracts/interchain-token-service/tests/query.rs
- contracts/interchain-token-service/tests/utils/execute.rs
need to migrate the existing chain configs
https://axelarnetwork.atlassian.net/browse/AXE-7486
accompanying PR in contract deployment repo: https://github.com/axelarnetwork/axelar-contract-deployments/pull/563
> refactor(minor-interchain-token-service): change max uint to max bits

- CHANGELOG.md
> chore: update changelog for ampd v1.5.0

- CHANGELOG.md
> chore: update changelog for ampd v1.5.1

- .github/workflows/build-ampd-release.yaml
> fix(release): add pat for checkout token

- ampd/src/commands/register_public_key.rs
- ampd/src/config.rs
- ampd/src/handlers/config.rs
- ampd/src/handlers/multisig.rs
- ampd/src/lib.rs
- ampd/src/tests/config_template.toml
Instead of using one `ampd` multisig handler for all signing sessions, switch to use a separate multisig handler per chain. Signing will run in parallel for several chains, although the number of tasks will increase dramatically. Each chain has a dedicated `ampd` voting handler already, so it makes sense to do the same for signing.
**NOTE**: This requires verifiers to update their `ampd` configs:
```diff
[[handlers]]
type = 'MultisigSigner'
cosmwasm_contract = 'axelar1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqecnww6'
+ chain_name = 'flow'
+
+ [[handlers]]
+ type = 'MultisigSigner'
+ cosmwasm_contract = 'axelar1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqecnww6'
+ chain_name = 'hedera'
```
- [EnsurePermissions](https://github.com/axelarnetwork/axelar-amplifier/blob/38321b7 …
> feat(ampd): separate multisig config per chain

- ampd/src/evm/verifier.rs
- ampd/src/mvx/verifier.rs
- ampd/src/starknet/verifier.rs
- ampd/src/stellar/verifier.rs
- ampd/src/sui/verifier.rs
fixes chain name comparison to make it case insensitive
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e526867c91905d03a6a8b1a41110b/packages/axelar-wasm-std-derive/src/lib.rs#L160): Event …
> fix(ampd): chain name comparison

- ampd/src/xrpl/verifier.rs
- packages/xrpl-types/src/msg.rs
Use `ChainNameRaw` instead of `ChainName` in `XRPLInterchainTransferMessage` and `XRPLCallContractMessage ` destination chain.
`test_verify_interchain_transfer_memos` fails when `ChainName` is used instead of `ChainNameRaw`, because `ChainName` converts "Ethereum" to lowercase "ethereum", while the `destination_chain` memo field has value `hex("Ethereum")`.
The same fix was applied to other intergrations' `ampd` verifiers here: https://github.com/axelarnetwork/axelar-amplifier/pull/785.
- [IntoContractError](https://github.com/axelarnetwork/axelar-amplifier/blob/eeb4406c7a0af04ec3afd8fcc39e65e6f2e69f7d/packag …
> fix(ampd): use ChainNameRaw for destination chain

- .github/actions/release/action.yaml
- .github/workflows/release.yaml
- ampd-handlers/src/main.rs
> feat(ampd-sdk): setup initial ci/cd pipeline

- ampd/src/evm/verifier.rs
- ampd/src/handlers/stellar_verify_msg.rs
- ampd/src/handlers/testdata/stellar_verify_msg_should_deserialize_correct_event.golden
- ampd/src/mvx/verifier.rs
- ampd/src/starknet/verifier.rs
- ampd/src/stellar/verifier.rs
- ampd/src/sui/verifier.rs
> fix(ampd): change type to ChainName in stellar Message

- ampd/src/evm/verifier.rs
- ampd/src/handlers/stellar_verify_msg.rs
- ampd/src/mvx/verifier.rs
- ampd/src/stellar/verifier.rs
- ampd/src/sui/verifier.rs
This cherrypicks these PRs:
https://github.com/axelarnetwork/axelar-amplifier/pull/785
https://github.com/axelarnetwork/axelar-amplifier/pull/787
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e5 …
> fix(ampd): backport chain name case insensitive comparisons

- .github/workflows/build-ampd-release.yaml
- .github/workflows/release.yaml
> feat(ci): add dry run option to ampd release job

- packages/xrpl-types/src/types.rs
For nonstandard currencies, the first 8 bits should **not** be `0x00`. 
Reference: https://xrpl.org/docs/references/protocol/data-types/currency-formats#nonstandard-currency-codes
> fix(xrpl-types): expected format for nonstandard currencies

- .github/workflows/build-ampd-release.yaml
> fix(ci): ampd dry run release condition 

- .cargo/config.toml
fix to this failed job: https://github.com/axelarnetwork/axelarate/actions/runs/14266972698/job/39991110607
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e526867c91905d03a6a8b1a41110b/packages/a …
> fix: rust optimizer git dependencies breaking

- .github/workflows/build-ampd-main.yaml
> fix(ci): recursive checkout for ampd docker build

- contracts/multisig/src/contract/execute.rs
- contracts/multisig/src/key.rs
- contracts/multisig/src/signing.rs
- contracts/multisig/src/state.rs
> feat(multisig): use error-stack to keep error contexts

- contracts/interchain-token-service/src/contract/migrations/mod.rs
- contracts/interchain-token-service/src/contract/migrations/v1_1_0.rs
- contracts/interchain-token-service/src/contract/migrations/v1_1_1.rs
- contracts/interchain-token-service/src/shared.rs
> fix(interchain-token-service): fix migration to handle all values

- Cargo.lock
- ampd/Cargo.toml
> fix: use latest open ssl version based on audit result

- Cargo.lock
- ampd/Cargo.toml
- ampd/src/config.rs
- ampd/src/grpc/blockchain_service.rs
- ampd/src/grpc/crypto_service.rs
- ampd/src/grpc/mod.rs
- ampd/src/lib.rs
- ampd/src/testdata/deserialize_valid_grpc_config.golden
- ampd/src/tests/config_template.toml
- packages/ampd-proto/build.rs
- packages/axelar-wasm-std/src/nonempty/mod.rs
- packages/axelar-wasm-std/src/nonempty/uint.rs
> feat(minor-ampd): create the gRPC server with todo's in services

- .github/workflows/dependabot-vulns-to-slack.yaml
- Cargo.lock
- Cargo.toml
> fix(ci): update webhook URL for slack notifications and tokio to 1.44.2

- ampd/src/event_sub/mod.rs
- ampd/src/grpc/blockchain_service.rs
- ampd/src/grpc/error.rs
- ampd/src/grpc/event_filters.rs
- ampd/src/grpc/mod.rs
- ampd/src/lib.rs
- ampd/src/types/mod.rs
- contracts/voting-verifier/src/events.rs
- packages/ampd-sdk/src/grpc/client.rs
- packages/axelar-wasm-std/src/msg_id/base_58_event_index.rs
- packages/axelar-wasm-std/src/msg_id/base_58_solana_event_index.rs
- packages/axelar-wasm-std/src/msg_id/starknet_field_element_event_index.rs
- packages/axelar-wasm-std/src/msg_id/tx_hash.rs
- packages/axelar-wasm-std/src/msg_id/tx_hash_event_index.rs
- packages/axelar-wasm-std/src/nonempty/string.rs
- packages/events/src/event.rs
> feat(minor-ampd): implement gRPC method subscribe for the blockchain service

- ampd/src/broadcaster_v2/broadcaster.rs
- ampd/src/broadcaster_v2/mod.rs
- ampd/src/broadcaster_v2/msg_queue.rs
- ampd/src/grpc/blockchain_service.rs
- ampd/src/grpc/error.rs
- ampd/src/grpc/mod.rs
- ampd/src/grpc/reqs.rs
- ampd/src/lib.rs
> feat(minor-ampd): implement gRPC method broadcast for the blockchain service

- ampd-handlers/Dockerfile
> feat(ampd-handlers): add wget to docker file

- Cargo.lock
- Cargo.toml
- contracts/multisig-prover/Cargo.toml
- contracts/multisig-prover/src/contract.rs
- contracts/multisig-prover/src/contract/execute.rs
- contracts/multisig-prover/src/encoding/mod.rs
- contracts/multisig-prover/src/lib.rs
- contracts/multisig-prover/src/msg.rs
- contracts/multisig-prover/src/state.rs
- contracts/voting-verifier/Cargo.toml
- contracts/voting-verifier/src/msg.rs
- integration-tests/Cargo.toml
- integration-tests/src/multisig_prover_contract.rs
- packages/multisig-prover-api/Cargo.toml
- packages/multisig-prover-api/src/encoding.rs
- packages/multisig-prover-api/src/lib.rs
- packages/multisig-prover-api/src/msg.rs
- packages/voting-verifier-api/Cargo.toml
- packages/voting-verifier-api/src/lib.rs
- packages/voting-verifier-api/src/msg.rs
> refactor: create prover and verifier api

- Cargo.lock
- ampd/Cargo.toml
- ampd/src/grpc/mod.rs
> feat(patch-ampd): add logging to the gRPC server

- ampd/src/grpc/blockchain_service.rs
- ampd/src/grpc/crypto_service.rs
> chore(ampd): replace todo! with unimplemented status code

- ampd/src/broadcaster_v2/msg_queue.rs
- ampd/src/grpc/blockchain_service.rs
> feat(minor-ampd): implement blockchain service method address

- ampd/src/cosmos.rs
- ampd/src/grpc/mod.rs
- ampd/src/tofnd/error.rs
> fix(patch-ampd): make gRPC-related errors transparent

- .github/workflows/ampd-handlers-docker-ecr.yaml
- .github/workflows/build-ampd-main.yaml
> refactor(ci): use 16-core runners for builds

- packages/axelar-wasm-std/src/nonempty/string.rs
> feat(axelar-wasm-std): compile-time safe nonempty string macro

- ampd/src/commands/register_public_key.rs
- ampd/src/grpc/crypto_service.rs
- ampd/src/grpc/reqs.rs
> feat(minor-ampd): implement crypto service method sign

- contracts/coordinator/src/contract/query.rs
- contracts/coordinator/src/msg.rs
- integration-tests/tests/coordinator_one_click_deployment.rs
- integration-tests/tests/test_utils/mod.rs
- packages/multisig-prover-api/src/msg.rs
> refactor(coordinator): refactor coordinator messages

- Cargo.lock
- contracts/coordinator/src/contract.rs
- contracts/coordinator/src/contract/execute.rs
- contracts/coordinator/src/events.rs
- contracts/coordinator/src/lib.rs
- contracts/coordinator/src/msg.rs
- integration-tests/Cargo.toml
- integration-tests/tests/coordinator_one_click_deployment.rs
> refactor(coordinator): refactor coordinator events

- contracts/multisig-prover/src/test/test_utils.rs
- contracts/service-registry/src/lib.rs
- contracts/voting-verifier/src/contract.rs
> fix(service-registry): remove internal verifier weight state from public interface

- ampd/src/config.rs
- ampd/src/handlers/config.rs
- ampd/src/json_rpc.rs
- ampd/src/lib.rs
- ampd/src/tofnd/mod.rs
- ampd/src/url.rs
[AXE-9672](https://axelarnetwork.atlassian.net/browse/AXE-9672) (https://axelarnetwork.atlassian.net/browse/AXE-9672)
```
impl Debug for Config {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
f.debug_struct("Config")
.field("tm_jsonrpc", &self.tm_jsonrpc)
.field("tm_grpc", &self.tm_grpc)
.field("tm_grpc_timeout", &self.tm_grpc_timeout)
.field("broadcast", &self.broadcast)
.field("handlers", &self.handlers)
.field("tofnd_config", &self.tofnd_config)
.field("event_processor", &self.event_processor)
.field("service_registry", &self.service_registry)
.field("rewards", &self.rewards)
.field("health_check_bind_addr", &REDACTED_VALUE)
// fmt::Debug is already redacted for field gprc
// (@see: src/grpc/mod.rs)
.field("grpc", &self.grpc)
.finish()
}
}
```
could be removed after the …
> refactor(url): add support for sensitivity and redacted logging 

- ampd/src/lib.rs
`to_string()` is calling the `Display` trait, which redacts sensitive `Url`s
> fix(ampd): do not use redacted string when initializing HttpClient

- contracts/service-registry/src/contract.rs
- contracts/service-registry/src/contract/execute.rs
- contracts/service-registry/src/state.rs
- integration-tests/tests/test_utils/mod.rs
- packages/service-registry-api/src/error.rs
AXE-9631
Added counter storage: AUTHORIZED_VERIFIER_COUNT map tracks authorized verifiers per service
prevent AuthorizeVerifiers if that exceeds the allowable number of verifiers
prevent UpdateService if a new lower max is set and that is below the current number of authorized verifiers
- [IntoContractError](https://github.com/axelarnetwork/axelar-amplifier/blob/eeb4406c7a0af04ec3afd8fcc39e65e6f2e69f7d/packages/axelar-wasm-std-derive/src/lib.rs#L12): Conversion from custom contract errors to [axelar_wasm_std::error::ContractError](https://github.com/axelarnetwork/axelar-amplifier/blob/eeb4406c7a0af04ec3afd8fc …
> feat(service-registry): enforce max verifier set limit in service registry

- packages/xrpl-types/src/error.rs
- packages/xrpl-types/src/msg.rs
Implements the `TryFrom<String>` trait for `XRPLMessageType`. This is currently used only by the relayer.
> feat(xrpl-types): implement TryFrom<String> for XRPLMessageType

- ampd/src/event_processor.rs
- ampd/src/monitoring/server.rs
- Replace hardcoded ports with OS-assigned ports using `TcpListener::bind` with port 0
- Add `TcpConnector` abstraction to support both `SocketAddr` and existing `TcpListener`
- Update tests to use OS-selected ports to prevent conflicts during parallel test execution
> fix(ampd): prevent port collisions in monitoring server tests

- ampd/src/broadcaster_v2/confirmer.rs
- ampd/src/broadcaster_v2/mod.rs
- ampd/src/commands/bond_verifier.rs
- ampd/src/commands/claim_stake.rs
- ampd/src/commands/deregister_chain_support.rs
- ampd/src/commands/mod.rs
- ampd/src/commands/register_chain_support.rs
- ampd/src/commands/register_public_key.rs
- ampd/src/commands/send_tokens.rs
- ampd/src/commands/set_rewards_proxy.rs
- ampd/src/commands/unbond_verifier.rs
Tries to fix this: https://github.com/axelarnetwork/axelarate/actions/runs/16352480999/job/46204604718
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e526867c91905d03a6a8b1a41110b/packages/axelar-wasm- …
> fix(ampd): add tx confirmation when executing commands 

- contracts/multisig/src/contract/migrations/mod.rs
A recent change added the coordinator's address to the multisig contract's instantiate message. This warrants a minor release update. Despite this, the release workflow was generating a patch update. The purpose of this PR is to cause the release workflow to generate a minor update by placing 'minor-multisig' in the conventional commit message.
- [IntoContractError](https://github.com/axelarnetwork/axelar-amplifier/blob/eeb4406c7a0af04ec3afd8fcc39e65e6f2e69f7d/packages/axelar-wasm-std-derive/src/lib.rs#L12): Conversion from custom contract errors to [axelar_wasm_std::error::ContractError](https://github.com/axelarn …
> fix(minor-multisig): minor multisig update to version 2.2.0

- .github/actions/release/action.yaml
- .github/actions/setup-rust/action.yml
- .github/workflows/ampd-handlers-docker-ecr.yaml
- .github/workflows/basic.yaml
- .github/workflows/build-ampd-main.yaml
- .github/workflows/build-ampd-release.yaml
- .github/workflows/build-contracts-and-push-to-r2.yaml
- .github/workflows/codecov.yaml
- .github/workflows/conventional-commits.yaml
- .github/workflows/dependabot-vulns-to-slack.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
- .github/workflows/security-audit.yaml
make sure we pin specific version in when using github marketplace actions or external tools 
(more details [here](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash)).
> fix: pin the github actions being used in the workflows

- .github/actions/setup-rust/action.yml
- .github/workflows/basic.yaml
The CI was experiencing toolchain version conflicts where a cached or default `stable` toolchain was interfering with the version specified in `rust-toolchain.toml` (1.86.0). This caused inconsistent behavior and failures in CI jobs.
- Remove the default `stable` toolchain before setting up the project-specific toolchain
- This ensures all CI steps consistently use the Rust version defined in `rust-toolchain.toml`
- **`.github/actions/setup-rust/action.yml`**: Added step to uninstall `stable` toolchain before setup
- **`.github/workflows/basic.yaml`**: Removed workaround that was uninstalling stable/nightly versions
The changes have been tested through multiple CI runs to ensure the toolchain setup works correctly without conflicts.
- ✅ Ensures consistent Rust version across all CI jobs
- …
> ci: fix rust toolchain conflicts in GitHub Actions

- ampd/README.md
- ampd/src/broadcast/config.rs
- ampd/src/broadcast/confirmer.rs
- ampd/src/commands/mod.rs
- ampd/src/config.rs
- ampd/src/event_processor.rs
- ampd/src/event_sub/mod.rs
- ampd/src/event_sub/stream.rs
- ampd/src/lib.rs
- ampd/src/monitoring/endpoints/metrics.rs
- ampd/src/monitoring/server.rs
- ampd/src/monitoring/testdata/ensure_correct_default_config.golden
- ampd/src/testdata/deserialize_valid_grpc_config.golden
- ampd/src/tests/config_template.toml
- ampd/src/tm_client.rs
This PR refactors several previously hardcoded constants into configurable fields in ampd:
**Broadcast:** moved `TX_CONFIRMATION_BUFFER_SIZ`E and `TX_CONFIRMATION_QUEUE_CAP` into broadcast::Config.
**Event Processor:** moved `TX_BROADCAST_BUFFER_SIZE `into event_processor::Config.
**Event Sub**: creatse  `event_sub::Config`. and moved `BLOCK_PROCESSING_BUFFER`, `POLL_INTERVAL`, and `retry policy` into it
**Monitoring:** added `channel_size` field to` monitoring::Config `and updated server initialization accordingly.
**Tendermint Client**: added `tm_client::Config` for retry parameters (max_retries, retry_delay).
**lib**: moved` default_rpc_timeout` into config
> refactor(ampd): move hardcoded values into config 

- .github/workflows/basic.yaml
This PR sets the exact version to be used for cargo-dylint and dylint-link packages to the last stable version which does not require `rustc 1.88`.
- [IntoEvent](https://github.com/axelarnetwork/axelar-amplifier/blob/27318df3e22e52686 …
> fix(ci): pin dylint cargo package versions
